name: Linters

on:
  pull_request:
  # Build when a pull request targets main
    branches:
      - main

permissions:
  contents: read

jobs:
  linter:
    name: Lint checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
        name: Checkout the repository
        with:
          fetch-depth: 100
          persist-credentials: true
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Check example keywords
        run: python3 doc/example-keywords.py compare
      - name: Get changed C++ files
        if: success() || failure()
        id: changed-cxx-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files: |
            **.h
            **.cpp
      # Comment blocks starting with "/*!" do not support autobrief
      - name: Check for problematic Doxygen comment blocks
        if: (success() || failure()) && steps.changed-cxx-files.outputs.any_changed == 'true'
        run: |
          RETCODE=0
          for file in ${ALL_CHANGED_FILES}; do
            RESULT=`perl -0777 -ne 'while(m/\n\n *\/\*!.*?\*\//gs){print "$&\n";}' $file`
            if [ "$RESULT" ]; then
              echo ------ ${file} ------
              echo "$RESULT"
              RETCODE=1
            fi
          done
          exit $RETCODE
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-cxx-files.outputs.all_changed_files }}
      - name: Whitespace errors
        if: success() || failure()
        run: |
          # These are files that should be ignored for whitespace checks
          echo ".gitmodules -diff" >> .gitattributes
          echo "*.sln -diff" >> .gitattributes
          echo "test/data/*.inp -diff" >> .gitattributes
          echo "test/data/*.xml -diff" >> .gitattributes
          echo "test/data/*.cti -diff" >> .gitattributes
          echo "test_problems/**/*blessed* -diff" >> .gitattributes

          git config --global core.autocrlf false
          git config --global core.whitespace \
            -cr-at-eol,tab-in-indent,blank-at-eol,blank-at-eof
          git diff --check ${{ github.event.pull_request.base.sha }}
      # Static type checking for Python interface
      - name: Install mypy, basedpyright, and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy basedpyright numpy ruamel.yaml pandas pandas-stubs \
            pint graphviz setuptools typing_extensions
      - name: Run mypy
        working-directory: interfaces/cython
        run: mypy --config-file pyproject.toml --python-version 3.10
      - name: Run basedpyright
        if: failure() || success()
        working-directory: interfaces/cython
        run: basedpyright --pythonversion 3.10
