name: CI

on:
  push:
    # Build on tags that look like releases
    tags:
      - v*
    # Build when main, testing, or the maintenance branch is pushed to
    branches:
      - main
      - testing
      # This workflow does not publish artifacts, so we can ignore the cache
      # poisoning finding.
      - "3.1" # zizmor: ignore[cache-poisoning]
  pull_request:
    # Build when a pull request targets main or the maintenance branch
    branches:
      - main
      - "3.1"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-multiple-pythons:
    name: ${{ matrix.os }} with Python ${{ matrix.python-version }}, Numpy ${{ matrix.numpy || 'latest' }}, Cython ${{ matrix.cython || 'latest' }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10']
        os: ['ubuntu-24.04']
        numpy: ['']
        cython: ['!=3.1.2'] # Specifier can be dropped after 3.1.3 or 3.2.0 is released
      fail-fast: false
    steps:
    - uses: actions/checkout@v5
      name: Checkout the repository
      with:
        submodules: recursive
        persist-credentials: false
    - name: Check out updated example data
      if: github.event_name == 'pull_request'
      env:
        BASE_PR: ${{ github.event.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd data/example_data
        gh repo set-default Cantera/cantera-example-data
        DATA_PR=$(gh pr list --repo Cantera/cantera-example-data --jq '.[] | select(.title | test("Cantera/cantera#'${BASE_PR}'")) | .number'  --json title,number)
        if [ -n "$DATA_PR" ]; then
          gh pr checkout --repo Cantera/cantera-example-data $DATA_PR
        fi
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install Apt dependencies
      run: |
        sudo apt update
        sudo apt install libboost-dev gfortran libopenmpi-dev libopenblas-openmp-dev \
          libhdf5-dev libfmt-dev doxygen
        gcc --version
    - name: Upgrade pip
      run: python3 -m pip install -U pip setuptools wheel
    - name: Install Python dependencies
      run: |
        python3 -m pip install ruamel.yaml scons==4.0.1 numpy${{ matrix.numpy }} \
          cython${{ matrix.cython }} pandas pytest \
          pytest-github-actions-annotate-failures pytest-xdist pint graphviz Jinja2
    - name: Build Cantera with legacy CLib
      run: |
        python3 `which scons` build env_vars=all -j4 debug=n --debug=time \
        system_fmt=y cc_flags=-D_GLIBCXX_ASSERTIONS clib_legacy=y
    - name: Build Tests
      run:
        python3 `which scons` -j4 build-tests --debug=time
    - name: Run compiled tests
      run: python3 `which scons` test-gtest test-legacy --debug=time
    - name: Run Python tests
      run: |
        LD_LIBRARY_PATH=build/lib
        python3 -m pytest -raP -v -n auto --durations=50 test/python
    - name: Rebuild Cantera with generated CLib
      run: |
        python3 `which scons` build  clib_legacy=n -j4
      if: matrix.python-version == '3.11'
    - name: Run googletests for generated CLib
      run: scons test-clib --debug=time
      if: matrix.python-version == '3.11'
    - name: Upload shared library
      # Pin to 4.3.4 to resolve errors around only uploading symlinks.
      # See https://github.com/actions/upload-artifact/issues/589
      uses: actions/upload-artifact@v4.3.4
      if: matrix.python-version == '3.10'
      with:
        path: build/lib/libcantera_shared.so
        name: libcantera_shared-${{ matrix.os }}.so
        retention-days: 2
    - name: Create archive for Doxygen output
      run: tar -czf doxygen.tar.gz Cantera.tag  doxygen/xml
      working-directory: build/doc
      if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-24.04'
    - name: Upload Doxygen output
      # Only need one copy from CI run
      uses: actions/upload-artifact@v4
      with:
        path: build/doc/doxygen.tar.gz
        name: doxygen-tree
        overwrite: true
        retention-days: 2
      if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-24.04'
    - name: Save the wheel file to install Cantera
      uses: actions/upload-artifact@v4
      with:
        path: build/python/dist/cantera*.whl
        retention-days: 2
        name: cantera-wheel-${{ matrix.python-version }}-${{ matrix.os }}
        if-no-files-found: error

  type-checking:
    name: Verify typing correctness and coverage of the public Python API
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    needs: ["ubuntu-multiple-pythons"]
    strategy:
      fail-fast: false
    steps:
      # Only need pyproject.toml for type checker settings
      - name: Checkout the repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install Apt dependencies
        run: |
          sudo apt update
          sudo apt install graphviz libhdf5-dev libfmt-dev libopenblas-openmp-dev
      - name: Download the wheel artifact
        uses: actions/download-artifact@v5
        with:
          name: cantera-wheel-3.10-ubuntu-24.04
          path: dist
      - name: Download the Cantera shared library (.so)
        uses: actions/download-artifact@v5
        with:
          name: libcantera_shared-ubuntu-24.04.so
          path: build/lib
      - name: Set up environment
        run: |
          ln -s libcantera_shared.so build/lib/libcantera_shared.so.3
          echo "LD_LIBRARY_PATH=build/lib" >> $GITHUB_ENV
          mkdir -p type_check
      - name: Upgrade pip
        run: python3 -m pip install -U pip setuptools wheel
      - name: Install Python dependencies
        run: |
          python3 -m pip install numpy ruamel.yaml pandas pandas-stubs \
            scipy pint graphviz typing_extensions pyright mypy[reports]
          python3 -m pip install --pre --no-index --find-links dist cantera
      - name: Check static type correctness with mypy
        run: |
          mypy --config-file interfaces/cython/pyproject.toml \
            -p cantera | tee type_check/mypy_check.txt
      - name: Generate coverage report with mypy
        if: failure() || success()
        run: |
          mypy --config-file interfaces/cython/pyproject.toml \
            --cobertura-xml-report type_check/ interfaces/cython/cantera
      - name: Summarize the report
        uses: danielpalme/ReportGenerator-GitHub-Action@9870ed167742d546b99962ff815fcc1098355ed8 # v5.4.17
        with:
          reports: './type_check/cobertura.xml'
          targetdir: './type_check'
          reporttypes: 'MarkdownSummaryGithub'
      - run: cat ./type_check/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        shell: bash
      - name: Generate coverage report with pyright
        if: failure() || success()
        run: |
          pyright --ignoreexternal --verifytypes cantera \
            | tee type_check/pyright_verifytypes.txt
      - name: Check type correctness against runtime with stubtest
        if: failure() || success()
        run: |
          stubtest --mypy-config-file interfaces/cython/pyproject.toml \
            --ignore-disjoint-bases --allowlist interfaces/cython/.mypyignore \
            --concise cantera | tee type_check/stubtest_concise.txt
          stubtest --mypy-config-file interfaces/cython/pyproject.toml \
            --ignore-disjoint-bases --allowlist interfaces/cython/.mypyignore \
            cantera >> type_check/stubtest_detailed.txt
          stubtest --mypy-config-file interfaces/cython/pyproject.toml \
            --ignore-disjoint-bases --allowlist interfaces/cython/.mypyignore \
            --generate-allowlist cantera >> type_check/stubtest_allowlist.txt
      - name: Archive Python API type checking results
        if: failure() || success()
        uses: actions/upload-artifact@v4
        with:
          name: python-type-check-reports
          path: type_check/*
          retention-days: 5
